version: '1.0.{build}'
configuration:
- Release
platform: Any CPU
before_build:
- appveyor-retry dotnet restore -v Minimal
build_script:
- dotnet build --no-dependencies -c %CONFIGURATION%
after_build:
- dotnet pack -c %CONFIGURATION% --no-build -o APPVEYOR_BUILD_FOLDER\artifacts
- dotnet publish -c %CONFIGURATION% -o APPVEYOR_BUILD_FOLDER\artifacts\Darwin
- dir
test_script:
- dotnet test "tests\WebSocketServer.Tests" -c %CONFIGURATION% -r APPVEYOR_BUILD_FOLDER\artifacts
- dotnet test "tests\GameLib.Tests" -c %CONFIGURATION% -r APPVEYOR_BUILD_FOLDER\artifacts
artifacts:
- path: artifacts\**\*.*
cache:
- '%USERPROFILE%\.nuget\packages'