version: '1.0.{build}'
configuration:
- Release
platform: Any CPU
before_build:
- dotnet --info
- appveyor-retry dotnet restore -v Minimal
build_script:
- dotnet build -c %CONFIGURATION%
after_build:
- dotnet pack -c %CONFIGURATION% --no-build -o artifacts
- dotnet publish -c %CONFIGURATION% --no-build -o artifacts\Darwin
test_script:
- dotnet test "tests\WebSocketServer.Tests" -c %CONFIGURATION% -r artifacts
- dotnet test "tests\GameLib.Tests" -c %CONFIGURATION% -r artifacts
artifacts:
- path: Darwin\artifacts\**\*.*