version: '1.0.{build}'
configuration:
- Release
platform: Any CPU
before_build:
- appveyor-retry dotnet restore -v Minimal
build_script:
- dotnet build -c %CONFIGURATION%
test_script:
- dotnet test "tests\WebSocketServer.Tests" -c %CONFIGURATION%
- dotnet test "tests\GameLib.Tests" -c %CONFIGURATION%