version: '3'
 
services:
  api:
    image: hspirdal/darwin.api
    build:
      context:  ./src/Services/Darwin.Api
      dockerfile: Dockerfile.debug
    ports:
      - 5001:80
    volumes: 
      - ./src/Services/Darwin.Api/bin/pub/:/app
    container_name: darwin.api
    environment:
      - RedisHost=redis.cache:6379
    depends_on:
      - redis.cache

  websocketserver:
    image: hspirdal/darwin.websocketserver
    build:
      context: ./src/WebSocketServer
      dockerfile: Dockerfile.debug
    ports:
      - 5000:80
    volumes: 
      - ./src/WebSocketServer/bin/pub/:/app
    container_name: websocketserver
    environment:
      - WebSocketServerHost=websocketserver
      - RedisHost=redis.cache:6379
      - MapWidth=80
      - MapHeight=80
      - ItemsPerCellPercent=0.01
      - creaturesPerCellPercent=0.01
      - GameTickMiliseconds=100
    depends_on:
      - redis.cache

  redis.cache:
    image: redis