version: '2'
 
services:
  api:
    image: hspirdal/darwin.api
    build:
      context:  ./src
      dockerfile: ./Services/Darwin.Api/Dockerfile
    ports:
      - 5001:80
    environment:
      - RedisHost=redis.cache:6379
    depends_on:
      - redis.cache

  websocketserver:
    image: hspirdal/darwin.websocketserver
    build:
      context: ./src
      dockerfile: ./WebSocketServer/Dockerfile
    ports:
      - 5000:80
    environment:
      - WebSocketServerHost=websocketserver
      - RedisHost=redis.cache:6379
      - MapWidth=50
      - MapHeight=40
      - GameTickMiliseconds=100
    depends_on:
      - redis.cache

  redis.cache:
    image: redis