version: '3'
 
services:
  api:
    image: hspirdal/darwin.api
    build:
      context:  ./src
      dockerfile: ./Services/Darwin.Api/Dockerfile
    ports:
      - 5001:80
    container_name: darwin.api
    environment:
      - RedisHost=redis.cache:6379
    depends_on:
      - redis.cache

  websocketserver:
    image: hspirdal/darwin.websocketserver
    build:
      context: ./src
      dockerfile: ./WebSocketServer/Dockerfile
    ports:
      - 5000:80
    container_name: websocketserver
    environment:
      - WebSocketServerHost=websocketserver
      - RedisHost=redis.cache:6379
      - MapWidth=80
      - MapHeight=80
      - ItemsPerCellPercent=0.01
      - CreaturesPerCellPercent=0.01
      - GameTickMiliseconds=100
    depends_on:
      - redis.cache

  redis.cache:
    image: redis