version: '2'
 
services:
  api:
    image: hspirdal/darwin.api
    build:
      context:  ./src
      dockerfile: ./Services/Darwin.Api/Dockerfile
    ports:
      - 5000:80
    environment:
      - RedisHost=redis.cache:6379
    depends_on:
      - redis.cache

  # gameserver:
  #   image: hspirdal/darwin.gameserver
  #   build:
  #     context: ./src
  #     dockerfile: ./GameServer/Dockerfile
  #   environment:
  #     - RedisHost=redis.cache:6379
  #   depends_on:
  #     - redis.cache

  tcpgameserver:
    image: hspirdal/darwin.tcpgameserver
    build:
      context: ./src
      dockerfile: ./TcpGameServer/Dockerfile
    ports:
      - 4444:4445
    environment:
      - TcpGameServerHost=tcpgameserver
      - RedisHost=redis.cache:6379
    depends_on:
      - redis.cache

  redis.cache:
    image: redis