FROM microsoft/dotnet:2.1-aspnetcore-runtime
RUN mkdir app

#Install debugger
RUN apt-get update
RUN apt-get install curl -y unzip
RUN curl -sSL https://aka.ms/getvsdbgsh | bash /dev/stdin -v latest -l /vsdbg

EXPOSE 5000
WORKDIR app

#Keep the debugger container on
ENTRYPOINT ["tail", "-f", "/dev/null"]
#ENTRYPOINT ["dotnet", "WebSocketServer.dll"]